# Generated by Django 4.1 on 2023-08-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0008_customuser_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
