# Generated by Django 5.0 on 2024-05-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0015_afaregistration_location_alter_payment_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='mtn_api_status',
            field=models.BooleanField(default=True),
        ),
    ]
