# Generated by Django 4.2.4 on 2025-02-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0019_admininfo_ishare_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='at_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='mtn_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='telecel_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='telecel_service_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='ishare_source',
            field=models.CharField(blank=True, choices=[('Gyasi', 'Gyasi'), ('Value4Moni', 'Value4Moni'), ('Geosams', 'Geosams')], default='Value4Moni', max_length=250, null=True),
        ),
    ]
