# Generated by Django 4.2.4 on 2025-03-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0021_bigtimetransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigtimetransaction',
            name='bundle_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='isharebundletransaction',
            name='bundle_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtntransaction',
            name='bundle_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vodafonetransaction',
            name='bundle_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
