# Generated by Django 4.2.4 on 2025-08-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0022_bigtimetransaction_bundle_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='paystack_active',
            field=models.BooleanField(default=False),
        ),
    ]
