# Generated by Django 4.2.4 on 2025-08-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0023_admininfo_paystack_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Super Agent', 'Super Agent')], default='User', max_length=250),
        ),
    ]
